### ISSUE TITLE
class file for org.hamcrest.Matcher not found

### ISSUE THREAD

**Issue by Awesome-Bob** [PacktPublishing/Test-Driven-Development-with-Java#1]
assertThat(res).hasStatusCode(HttpStatus.NO_CONTENT.code);
                       ^
  class file for org.hamcrest.Matcher not found

**Comment by viewfromthecodeface** [comment]
fix for 
- Missing Hamcrest dependency
- Incorrect private visibility on before each method
- .gitgnore to exclude .idea/

Available in commit c558b32 (fixes chapter15 and chapter15+flyway)
